import clsx from 'clsx';

export const SpinnerBlock = ({
  fill,
  className,
}: {
  fill?: string;
  className?: string;
}) => {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill={fill}
      className={clsx(className)}
    >
      <rect x="1" y="1" rx="1" width="10" height="10">
        <animate
          id="spinner_c7A9"
          begin="0;spinner_23zP.end"
          attributeName="x"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
        <animate
          id="spinner_Acnw"
          begin="spinner_ZmWi.end"
          attributeName="y"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
        <animate
          id="spinner_iIcm"
          begin="spinner_zfQN.end"
          attributeName="x"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
        <animate
          id="spinner_WX4U"
          begin="spinner_rRAc.end"
          attributeName="y"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
      </rect>
      <rect x="1" y="13" rx="1" width="10" height="10">
        <animate
          id="spinner_YLx7"
          begin="spinner_c7A9.end"
          attributeName="y"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
        <animate
          id="spinner_vwnJ"
          begin="spinner_Acnw.end"
          attributeName="x"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
        <animate
          id="spinner_KQuy"
          begin="spinner_iIcm.end"
          attributeName="y"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
        <animate
          id="spinner_arKy"
          begin="spinner_WX4U.end"
          attributeName="x"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
      </rect>
      <rect x="13" y="13" rx="1" width="10" height="10">
        <animate
          id="spinner_ZmWi"
          begin="spinner_YLx7.end"
          attributeName="x"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
        <animate
          id="spinner_zfQN"
          begin="spinner_vwnJ.end"
          attributeName="y"
          dur="0.2s"
          values="13;1"
          fill="freeze"
        />
        <animate
          id="spinner_rRAc"
          begin="spinner_KQuy.end"
          attributeName="x"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
        <animate
          id="spinner_23zP"
          begin="spinner_arKy.end"
          attributeName="y"
          dur="0.2s"
          values="1;13"
          fill="freeze"
        />
      </rect>
    </svg>
  );
};

export const LoadingFlag = ({
  fill,
  className,
}: {
  fill?: string;
  className?: string;
}) => {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill={fill}
      className={className}
    >
      <rect x="1" y="1" width="7.33" height="7.33">
        <animate
          id="spinner_oJFS"
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="0;spinner_5T1J.end+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="1" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="1" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.1s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="1" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="1" y="15.66" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="x"
          dur="0.6s"
          values="1;4;1"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.2s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="8.33" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="y"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="8.33" y="15.66" width="7.33" height="7.33">
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="x"
          dur="0.6s"
          values="8.33;11.33;8.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.3s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
      <rect x="15.66" y="15.66" width="7.33" height="7.33">
        <animate
          id="spinner_5T1J"
          begin="spinner_oJFS.begin+0.4s"
          attributeName="x"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="y"
          dur="0.6s"
          values="15.66;18.66;15.66"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="width"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
        <animate
          begin="spinner_oJFS.begin+0.4s"
          attributeName="height"
          dur="0.6s"
          values="7.33;1.33;7.33"
        />
      </rect>
    </svg>
  );
};
